### ISSUE TITLE
quafu包错误

### ISSUE THREAD

**Issue by liujiefei** [ScQ-Cloud/pyquafu#130]
quafu包错误，在引入qfvm时报dll初始化例程失败，请问怎么解决
![image](https://github.com/ScQ-Cloud/pyquafu/assets/34298673/78f54daa-29a3-4e48-b8f3-cff738ed530e)

**Comment by Zhaoyilunnn** [comment]
很大概率是您的电脑处理器版本较旧，不支持AVX编译，类似这种：https://blog.csdn.net/weixin_44613728/article/details/115967299，我们之后发布新版Pyquafu会避免在初始化的时候Import模拟器，如果您不需要模拟器功能，可以修改一下源码，


打开您截图中"G: xxxx\simulators\simulator.py"这个文件，然后将```from .qfvm import xxx``` 这一行剪切移动到`simulate()`这个函数里面，参考：https://github.com/ScQ-Cloud/pyquafu/pull/116/files
