### ISSUE TITLE
Missing UnitaryDecomposer method

### ISSUE THREAD

**Issue by Shiyin0922** [ScQ-Cloud/pyquafu#152]
In version 0.3.6，UnitaryDecomposer method is in the following path \elements\element_gates\unitary\decomposer
Has the version 0.4.0 changed the name of this method to a different name or has the feature not been added yet?

**Comment by Zhaoyilunnn** [comment]
I believe `UnitaryDecomposer` in included in 0.4.0. See: https://github.com/ScQ-Cloud/pyquafu/blob/master/quafu/elements/unitary/decomposer.py#L12.

What is the exact error you met, could you please share the backtrace output

**Comment by Zhaoyilunnn** [comment]
![f6514d3ab95505bd0d745b06203c24a](https://github.com/ScQ-Cloud/pyquafu/assets/40353317/57259911-7464-4700-95da-d6f3f86c074f)

`qeg` now does not have `UnitaryDecomposer` imported, see https://github.com/ScQ-Cloud/pyquafu/blob/master/quafu/circuits/quantum_circuit.py#L1098
