### ISSUE TITLE
Keyerror in user.get_available_backends()

### ISSUE THREAD

**Issue by FrankC03** [ScQ-Cloud/pyquafu#167]
KeyError when accessing 'data' key in _get_backends_info response

![image](https://github.com/ScQ-Cloud/pyquafu/assets/167671711/f686c849-35bd-4e8c-b18a-3ba25356336e)

**Comment by Zhaoyilunnn** [comment]
Hello, Could you provide the version you use

**Comment by FrankC03** [comment]
Thank you for your assistance. It appears that my API token has expired. I have since refreshed it, and there are no longer any errors. Could you please advise on the recommended frequency for refreshing my API token? (pyquafu version 0.3.6)

**Comment by Zhaoyilunnn** [comment]
> Thank you for your assistance. It appears that my API token has expired. I have since refreshed it, and there are no longer any errors. Could you please advise on the recommended frequency for refreshing my API token? (pyquafu version 0.3.6)

You're welcome, yes for 0.3.6, the error message is not precise for now, we may make our backend backward compatible to show correct prompt about API token issue in the future. Also we have implemented better error handling and will release 0.4.0 soon, please stay tuned. 

I suggest that you refresh API token every 3 months.
