### ISSUE TITLE
Looking for an Existing Library for Randomized Benchmarking Experiments

### ISSUE THREAD

**Issue by FrankC03** [ScQ-Cloud/pyquafu#168]
Is there an existing library that provides Randomized Benchmarking experiments?

**Comment by FrankC03** [comment]
Thanks, I'm planning to implement RB myself. From your tutorial, I found guidance on sending tasks asynchronously. Could you please let me know if there's any way to batch save results and batch delete tasks efficiently? Any guidance or advice would be much appreciated.

**Comment by Zhaoyilunnn** [comment]
You could submit and retrieve a *group* of tasks and name the group for convenience (see the [document](https://scq-cloud.github.io/tutorial.html#submit-task-asynchronously)). 
Moreover, you could manage your tasks using a local database (please search `TaskDatabase` in the web page of documents)
Not sure if this is what you need for *batch save results*. 
However, we do not yet provide api for batch delete tasks, I believe you could do so directly on the [website](https://quafu.baqis.ac.cn/).

Happy to help if you have additional questions

**Comment by FrankC03** [comment]
Really appreciate your help; I'll try out your advice. Is it possible to implement batch deletion of tasks in the future? It can be quite a headache to delete hundreds of tasks individually on the website. :(

**Comment by Zhaoyilunnn** [comment]
pyquafu is still under heavy development and in its infancy, thanks for your suggestions. We will regularly review our development roadmap and may support 'bulk delete' in the future. You might subscribe this repository and get updates once new version released
