### ISSUE TITLE
Typeerror when I submit my circuit under the ueser guide

### ISSUE THREAD

**Issue by hanzichang123** [ScQ-Cloud/pyquafu#21]
when  I submit my circuit follow the user guide useing Python, there is a Typeerror:line 36, in <module>
    task = Task()
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quafu\tasks\tasks.py", line 36, in __init__
    self._available_backends = {info["system_name"]:Backend(info) for info in get_backends_info()}
TypeError: 'NoneType' object is not iterable
 
how can I solve it,and the following is the code:

#Set up your Quafu account
from quafu import User
user = User()
user.save_apitoken("<your API token>")
#Build your first quantum circuit
import numpy as np
from quafu import QuantumCircuit

q = QuantumCircuit(5)
q.x(0)
q.x(1) 
q.cnot(2, 1) 
q.ry(1, np.pi/2) 
q.rx(2, np.pi) 
q.rz(3, 0.1) 
q.cz(2, 3) 
measures = [0, 1, 2, 3]
cbits = [0, 1, 2, 3]
q.measure(measures,  cbits=cbits)
q.draw_circuit(width=4)
print(q)
qc = QuantumCircuit(4)
test_ghz = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
h q[0];
cx q[0],q[1];
cx q[0],q[2];
cx q[0],q[3];
"""
qc.from_openqasm(test_ghz)
qc.draw_circuit()
print(qc)
#Submit your circuit
from quafu import Task
task = Task()
task.config(backend="ScQ-P18", shots=2000, compile=True)
res = task.send(q)
print(res.counts) #counts
print(res.probabilities) #probabilities
res.plot_probabilities()

Thank you

**Comment by chensgit169** [comment]
It seems not the fault of coding but network communication, or because the chips are under maintenance. Simply try it again later.

**Comment by hanzichang123** [comment]
ok,thank you very much

chensgit169 ***@***.***> 于2023年5月27日周六 09:36写道：

**Comment by chensgit169** [comment]
You are welcome. I think we could add user-hint functions in a renewed version of quafu to make such issues apparent to the users. Please stay tuned for the future release :)

**Comment by hanzichang123** [comment]
you mean close this line and  by the way, may I consult what is meaning of
"user-hint function"
[image: image.png]

chen_wei ***@***.***> 于2023年5月27日周六 10:19写道：

**Comment by hanzichang123** [comment]
this is the whole code for Visual studio code in python

韩子长 ***@***.***> 于2023年5月27日周六 10:29写道：
