### ISSUE TITLE
Can't import User class successfully.

### ISSUE THREAD

**Issue by Alndaly** [ScQ-Cloud/pyquafu#28]
When user first use this python library, he or she will not be able to import User class successfully because of the `self.load_account()` in the `__init__` part of the User class.

![](https://oss.kinda.info/image/202307230025988.png)

**Comment by Alndaly** [comment]
I have already made a pr, please check it at https://github.com/ScQ-Cloud/pyquafu/pull/29.

**Comment by Zhaoyilunnn** [comment]
merged https://github.com/ScQ-Cloud/pyquafu/pull/29
