### ISSUE TITLE
quafu.users.exceptions.UserError: 'Current priority is not allowed'

### ISSUE THREAD

**Issue by zhangyu0217** [ScQ-Cloud/pyquafu#4]
Dear developers,

I meet the error as the title says

quafu.users.exceptions.UserError: 'Current priority is not allowed'

I am using python 3.8.5 and pyquafu 0.2.9.

I am just running the example and the priority is the default value "priority=2". The code is below.

Please let me know if I can do something to debug.

Thank you.

cheers,
Yu

from quafu import User
import numpy as np
from quafu import QuantumCircuit

qc = QuantumCircuit(4)
test_ghz = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
h q[0];
cx q[0],q[1];
cx q[0],q[2];
cx q[0],q[3];
"""
qc.from_openqasm(test_ghz)
qc.draw_circuit()

from quafu import Task
task = Task()
task.load_account()

task.config(backend="ScQ-P20", shots=2000, compile=True, priority=2)

print(task.priority)
res = task.send(qc)

print(res.counts) #counts
print(res.amplitudes) #amplitude
res.plot_amplitudes()

**Comment by bobeina** [comment]
Hi @zhangyu0217 Did you fix this? I got a core dump when I run first line:

from quafu import User

**Comment by zhangyu0217** [comment]
Hi @bobeina ,

I had a private chat with quafu maintainers and the problem was solved.
I have no idea about your problem.

cheers,
Yu

**Comment by ScQ-Cloud** [comment]
Hi @bobeina ,

Thanks for using PyQuafu! Have you tried to reinstall or update it, because we have updated the pip package in recent days.

**Comment by ScQ-Cloud** [comment]
Hi @zhangyu0217 , thanks for reporting a bug. Have a good job😁.

**Comment by bobeina** [comment]
@ScQ-Cloud I installed it two days ago.

After
`from quafu import User`

pycharm 2022.3.2 + virtualenv 20.13.0:
Process finished with exit code 132 (interrupted by signal 4: SIGILL)

With python console only:
Illegal instruction (core dumped)

**Comment by ScQ-Cloud** [comment]
@bobeina It seems that your CPU does not support AVX2.
This issue may help you https://stackoverflow.com/questions/49094597/illegal-instruction-core-dumped-after-running-import-tensorflow
