### ISSUE TITLE
Docs and save_apitoken

### ISSUE THREAD

**Issue by YunJ1e** [ScQ-Cloud/pyquafu#47]
By following the instruction on the docs website, 
```
from quafu import User
user = User()
user.save_apitoken("<your API token>")
```
will currently generate the error message, 

> UserWarning: The argument 'apitoken' in this function will be deprecated in the future, please set api token by providing 'api_token' or 'token_dir' when initialize User().
>   warnings.warn("The argument 'apitoken' in this function will be deprecated "

Could your team provide the new commands regarding saving the api-token and then update the documentation website?

**Comment by Zhaoyilunnn** [comment]
Please use: `user = User(api_token="xxxx")`

**Comment by Zhaoyilunnn** [comment]
> By following the instruction on the docs website,
> 
> ```
> from quafu import User
> user = User()
> user.save_apitoken("<your API token>")
> ```
> 
> will currently generate the error message,
> 
> > UserWarning: The argument 'apitoken' in this function will be deprecated in the future, please set api token by providing 'api_token' or 'token_dir' when initialize User().
> > warnings.warn("The argument 'apitoken' in this function will be deprecated "
> 
> Could your team provide the new commands regarding saving the api-token and then update the documentation website?

Please use: `user = User(api_token="xxxx")`, we will update the documentation website later, thanks

**Comment by YunJ1e** [comment]
Thanks, :)

**Comment by Zhaoyilunnn** [comment]
> Thanks, :)

No problem.
BTW, the complete usage is

```
user = User(api_token="xxxx")

# This saves apitoken to your disk for reuse
user.save_apitoken()
```
