### ISSUE TITLE
Bug: Measurement on subset of qubits

### ISSUE THREAD

**Issue by YunJ1e** [ScQ-Cloud/pyquafu#49]
**Bug Description:**
Measuring only a subset of the quantum circuit will return errors. 

**Code to Reproduce the Bug:**
The code is from the documentation website.
```
import numpy as np
from quafu import QuantumCircuit, Task
q = QuantumCircuit(3)
q.x(2)
q.delay(2, t, unit="us")
q.measure([2])
task = Task()
task.config(backend="ScQ-P18", shots=2000, compile=False)
res = task.send(q)
```

**Code Output:**
> IndexError: string index out of range

**My Debugging Trials:**
And if you change the one line of code `q.measure([2])` to `q.measure([0, 1, 2])` will simply solve the problem. But it would be better if your team could come up with proper solutions that could either prevent users from measuring subsets of qubits or support this feature.

**Comment by Zhaoyilunnn** [comment]
Thanks, looked into this issue

**Comment by Zhaoyilunnn** [comment]
We do support this 

> **Bug Description:** Measuring only a subset of the quantum circuit will return errors.
> 
> **Code to Reproduce the Bug:** The code is from the documentation website.
> 
> ```
> import numpy as np
> from quafu import QuantumCircuit, Task
> q = QuantumCircuit(3)
> q.x(2)
> q.delay(2, t, unit="us")
> q.measure([2])
> task = Task()
> task.config(backend="ScQ-P18", shots=2000, compile=False)
> res = task.send(q)
> ```
> 
> **Code Output:**
> 
> > IndexError: string index out of range
> 
> **My Debugging Trials:** And if you change the one line of code `q.measure([2])` to `q.measure([0, 1, 2])` will simply solve the problem. But it would be better if your team could come up with proper solutions that could either prevent users from measuring subsets of qubits or support this feature.

Partial measurement a supported feature, we are fixing this issue and will release assp

**Comment by Zhaoyilunnn** [comment]
Now you can build from `stable/0.3`

```
git checkout -b stable/0.3 origin/stable/0.3
python setup.py install
```

We will release new version to pypi later, closed

**Comment by YunJ1e** [comment]
Nice, thank you for your quick reaction. :^)

**Comment by Zhaoyilunnn** [comment]
> Nice, thank you for your quick reaction. :^)

NP, thanks for your contributions
