### ISSUE TITLE
Bug: Submit task asynchronously

### ISSUE THREAD

**Issue by YunJ1e** [ScQ-Cloud/pyquafu#50]
**Bug Description:**
Following docs code on _Submit task asynchronously_ will not give the proper output

**Code to Reproduce the Bug:**
The code is from the documentation website.
```
import numpy as np
from quafu import QuantumCircuit, Task
task = Task()
task.config(backend="ScQ-P10", shots=2000, compile=False, priority=2)

ts = range(0, 5, 1)
names = ["%dus" %t for t in ts]
for name, t in zip(names, ts): 
    q = QuantumCircuit(3)
    q.x(2)
    q.delay(2, t, unit="us")
    q.measure([2])
    res = task.send(q, wait=False, name=name, group="Q3_T1")

group_res = task.retrieve_group("Q3_T1")
probs = [res.probabilities["1"] for res in group_res]
```

**Code Output:**

> AttributeError: 'NoneType' object has no attribute 'values'

Those tasks are indeed uploaded to the cloud and could be seen on the website. But it seems like something goes wrong with the  `task.retrieve_group("Q3_T1")`

**My Debugging Trials:**
```
ts = range(0, 5, 1)
names = ["%dus" %t for t in ts]
result = []
for name, t in zip(names, ts): 
    q = QuantumCircuit(3)
    q.x(2)
    q.delay(2, t, unit="us")
    q.measure([2])
    task = Task()
    task.config(backend="ScQ-P10", shots=2000, compile=False)
    result.append(task.send(q, name=name))
```
will do the job similarly, but it is not _asynchronous_ I guess.

**Comment by Zhaoyilunnn** [comment]
Looked into this issue.
BTW. The document is out-of-date.... I would suggest you try `pip install pyquafu==0.2.11`
