### ISSUE TITLE
Failed to send tasks, ending up with KeyError from retrieve_group

### ISSUE THREAD

**Issue by Memcys** [ScQ-Cloud/pyquafu#6]
### The issue
I was trying to send the 17th of a sequence of tasks, when I came up with a `JSONDecodeError`, which I suppose was due to deep layers of gates:
```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Cell In[141], line 18
     15 # measurement in the computational basis
     16 measure(q)
---> 18 task.send(q, name=name, group="MFIM-compile", wait=False)

File /usr/local/lib/python3.10/site-packages/quafu/tasks/tasks.py:279, in Task.send(self, qc, name, group, wait)
    277 data = data.replace("%27", "'")
    278 res = requests.post(url, headers=headers, data=data)
--> 279 res_dict = json.loads(res.text)
    281 if res.json()["status"] in [201, 205]:
    282     raise UserError(res_dict["message"])

File /usr/local/lib/python3.10/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
    348     cls = JSONDecoder

File /usr/local/lib/python3.10/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
...
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
As I tried to retrieve the first 16 task results with
```python
group_res = task.retrieve_group("MFIM-compile")
```
I got a `KeyError` and nothing from `group_res`:
```
KeyError                                  Traceback (most recent call last)
Cell In[142], line 1
----> 1 group_res = task.retrieve_group("MFIM-compile")

File /usr/local/lib/python3.10/site-packages/quafu/tasks/tasks.py:340, in Task.retrieve_group(self, group, history, verbose)
    338     print((" "*5).join(["task_id".ljust(16), "task_name".ljust(10),   "status".ljust(10)]))
    339 for taskid in taskids:
--> 340     res = self.retrieve(taskid)
    341     taskname = res.taskname
    342     if verbose:

File /usr/local/lib/python3.10/site-packages/quafu/tasks/tasks.py:315, in Task.retrieve(self, taskid)
    312 res_dict = json.loads(res.text)
    313 measures = eval(res_dict["measure"])
--> 315 return ExecResult(res_dict, measures)

File /usr/local/lib/python3.10/site-packages/quafu/results/results.py:26, in ExecResult.__init__(self, input_dict, measures)
     24 status_map = {0:"In Queue", 1:"Running", 2:"Completed", "Canceled":3, 4:"Failed"}
     25 self.measures = measures
---> 26 self.task_status = status_map[input_dict["status"]]
     27 self.res = eval(input_dict['res'])
     28 self.counts = OrderedDict(sorted(self.res.items(), key=lambda s: s[0]))
```

### The question
How may I retrieve the completed 16 task results? Thanks in advance!

**Comment by ScQ-Cloud** [comment]
Like this
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/107848364/226093931-ad81431e-4ed6-4de2-a80e-22d1c64d3646.png">

**Comment by chensgit169** [comment]
Sorry that I just noticed this issue. I also met ``JSONDecodeError`` several days ago and had checked to find that ``res.text`` in ``task.send()`` was an empty string and value of ``res_dict['ok']`` in ``backend.get_backends_info()`` was ``False``. This problem seemed to originate from the backends, for my codes runs well several hours later without any modification. Please report it if you met similar error again to help trace the reason of error. Better exception handling may be implemented in the future.

**Comment by Memcys** [comment]
> Hi @Memcys, could you find these tasks on the web?

Sorry for this late reply. I did find them in the `History Tasks`.


> Sorry that I just noticed this issue. I also met `JSONDecodeError` several days ago and had checked to find that `res.text` in `task.send()` was an empty string and value of `res_dict['ok']` in `backend.get_backends_info()` was `False`. This problem seemed to originate from the backends, for my codes ran well several hours later without any modification. Please report it if you met similar error again to help trace the reason of error. Better exception handling may be implemented in the future.

Thank you for your comment and your guarantee. It does seem like an occasional error, for I received all results in later runs (though the circuits were modified somehow).
